### ISSUE TITLE
Ensure existing dosdp yamls conform to schema

### ISSUE THREAD

**Issue by cmungall** [INCATools/dead_simple_owl_design_patterns#26]
(this is a linker ticket that will be references from other repos)

Now we have a mature schema we should make sure existing yamls in the wild conform

## ontologies

 - [x] phenotype - https://github.com/obophenotype/upheno/pull/215
 - [ ] ecto
 - [ ] oba
 - [ ] envo
 
## tools

 - [x] pattern2owl. [DONE](https://github.com/cmungall/pattern2owl/commit/f09a662aebf580751ea1e3633411a6cb32876ead)

**Comment by dosumis** [comment]
Can be achieved with ODK
