### ISSUE TITLE
Conditional filtering in dosdps

### ISSUE THREAD

**Issue by msinclair2** [INCATools/dead_simple_owl_design_patterns#40]
Hi,

I originally posted a form of this question on the dosdp-tools repo, but Jim suggested it might be better here.

I have two related questions, maybe only one of them needs answering:

1) Is it possible to have conditional if-else style logic in a dosdp so dosdp-tools can only select certain classes based on specified variables? I'd like to know in any case, but probably the better approach is:

2) How can I write a pattern that will filter based on the presence or absence of a property, if this is possible? For example, how does one write a pattern that will select all classes with the annotation property owl:deprecated, in order to return a list of all deprecated classes? How does one do the inverse, select all classes that don't have the deprecation annotation to get a list of all currently valid classes?

Jim suggested that there isn't a way to do this with dosdp-tools.  He suggested using a SPARQL query with ROBOT as a pre-processing step for input to dosdp tools.  I know I can do the above in OWLAPI.  Would that be considered an inelegant solution?  I am not yet familiar with SPARQL.  What would be the best forum in which to ask for help with SPARQL (not here, of course :) )?

Thank you.

**Comment by dosumis** [comment]
Out of scope
