### ISSUE TITLE
Add an examples field

### ISSUE THREAD

**Issue by cmungall** [INCATools/dead_simple_owl_design_patterns#49]
I sometimes embed examples in the description field. It would be useful to have this more computable, e.g

```
examples:
 - GO:0009999
 - GO:....
```

**Comment by cmungall** [comment]
This could be combined with some way of specifying integration tests. E.g. 

 * we expect class X to conform to this pattern
 * ditto, and we expect the generated logical def to be ...
 * ditto, and we expect to be classified under Y
 * ...

**Comment by matentzn** [comment]
That’s a pretty cool idea!! You got my vote!

**Comment by matentzn** [comment]
@dosumis this keeps popping up! Would be good to get this!
