### ISSUE TITLE
Provide explanation for "substitution" field

### ISSUE THREAD

**Issue by matentzn** [INCATools/dead_simple_owl_design_patterns#70]
The point of the substitution field is currently unclear. Can we add a description?

**Comment by balhoff** [comment]
Here is an example usage, in case it's needed: https://github.com/geneontology/go-ontology/blob/master/src/design_patterns/activator_activity.yaml

**Comment by matentzn** [comment]
Wow! I did not know that was possible :)

**Comment by dosumis** [comment]
Should now be clear from auto-gen dock.  Please re-open if not.
