### ISSUE TITLE
Dictionary IRIs

### ISSUE THREAD

**Issue by trapperkeeper** [INCATools/dead_simple_owl_design_patterns#86]
This may be more of a question than an issue, but in reading documentation about dos-dp yaml specification, it says this about dictionaries:

"IDs must be OBO curie style e.g. CL:0000001"

Does that mean that dos-dp works only with OBO ontologies?

**Comment by balhoff** [comment]
If you are using the [dosdp-tools](https://github.com/INCATools/dosdp-tools) application, you can provide a prefixes file to define your own prefixes. It should work for any OWL ontologies. There is also a flag `--obo-prefixes` if you want it to assume unknown prefixes are OBO ontologies.

**Comment by trapperkeeper** [comment]
Thank you @balhoff, that is precisely what I needed to know. closing issue.
